# config/model_params.yaml
# ... (他のハイパーパラメータ設定) ...

Data:
  # 使用する特定のデータファイルを指定し、そのファイルが持つパラメータを記述する
  # ここでファイルパスを直接指定するか、ファイル名パターンを定義する
  # 例1: 特定のファイルを指定する場合
  # training_data_file: "zebrafish_features_processed_v1.0_20250617.csv"
  # training_data_params:
  #   time_window: 5
  #   step_size: 3
  #   overlap_ratio: 0.4

  # 例2: 複数のデータセットの組み合わせを定義する場合
  # スクリプトはこのリストをループして、対応するデータを読み込む
  dataset_configs:
    - name: "zebrafish_features_processed_tw05_ss03_v1.0.csv" # ファイル名で特徴を示すが、パラメータ自体はここで管理
      time_window: 5
      step_size: 3
      overlap_ratio: 0.4
    - name: "zebrafish_features_processed_tw15_ss06_v1.0.csv"
      time_window: 15
      step_size: 6
      overlap_ratio: 0.4
    # ... 他の組み合わせ